### ISSUE TITLE
Matching Column names when expecting a Query

### ISSUE THREAD

**Issue by juliusbachnick** [DATA-DOG/go-sqlmock#126] opened 2018-07-11 09:23 UTC
When using sqlmock und working with `ExpectQuery`, the column names of the mocked row are never matched against the ones in the query. Hence, any values could be provided as a column names for a mocked row. 

It would be really helpful (for the sake of test consistency) if the column names would also be matched.

If required, I could attach a simple example to illustrate the issue.

**Comment by l3pp4rd** [comment] 2018-07-11 10:13
Hi, yes example with an use case would be useful. sqlmock does not analyze the query regexp and uses it only to match sql. If you expect to match fields selected in query, that cannot be done properly.

**Comment by l3pp4rd** [comment] 2018-12-11 09:51
customized sql matcher would allow such behavior, closing as duplicate of #70

**Closed by l3pp4rd** 2018-12-11 09:51 UTC
